name = "WinchModels"
uuid = "7dcfa46b-7979-4771-bbf4-0aee0da42e1f"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.1.0"

[deps]
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
TestEnv = "1e6cf692-eddd-4d53-88a5-2d735e33781b"

[compat]
julia = "1"
TestEnv = "1"
Parameters = "0.12"
KiteUtils = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
